name: Build Ra-TEmbed

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository laden
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: PlatformIO installieren
        run: pip install platformio

      - name: T-Embed Firmware bauen
        run: pio run -e tembed_s3_test

      - name: Firmware umbenennen
        run: cp .pio/build/tembed_s3_test/firmware.bin Ra-TEmbed.bin

      - name: Firmware bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: Ra-TEmbed
          path: Ra-TEmbed.bin
